## Function to calculate Reduced Row Echelon Form

In [1]:
import numpy as np

'''Reduced Row Echelon Form'''
'''Input matrix should be float type.'''


def my_rref(m):

    if np.size(m) < 1: return print("This is an empty matrix.")
    pivot = 0
    row = np.shape(m)[0]
    column = np.shape(m)[1]

    for pre_row in range(row):
        i = pre_row
        'print("m_pivot:", m[i, pivot])'

        while m[i, pivot] == 0:
            print(i)
            i += 1
            if i >= row:
                i = pre_row
                pivot += 1
                if pivot >= column :
                    return print(m)
        m[(pre_row, i), :] = m[(i, pre_row), :]
        m[pre_row, :] = m[pre_row, :]/m[pre_row, pivot]
        '''print("pre_row:",m[pre_row, :])'''

        for i in range(row):

            if i != pre_row:
                m[i, :] = m[i, :] - m[i, pivot]*m[pre_row, :]
        pivot += 1
        if pivot >= column:
            return print(m)
    print(m)


a = np.array([[4,-2,-2,0],[-2,8,-3,-3],[-2,-3,8,-3],[0,-3,-3,6]],dtype=float)
print(a)
rref = my_rref(a)

[[ 4. -2. -2.  0.]
 [-2.  8. -3. -3.]
 [-2. -3.  8. -3.]
 [ 0. -3. -3.  6.]]
3
[[ 1.  0.  0. -1.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1. -1.]
 [ 0.  0.  0.  0.]]
